version: "3.3" 
services:
    websuite:
      image: gbdconsult/gws-server:7.0
      ports:
        - "3333:80"
      volumes:
        - "./data:/data"
      depends_on:
        - postgis
    postgis:
      image: postgis/postgis:15-master
      ports:
        - "54321:5432"
      volumes:
        - "pg_data:/var/lib/postgresql"
      environment:
        - POSTGRES_DB=fossgis
        - POSTGRES_USER=fossgis
        - POSTGRES_PASSWORD=fossgis
      restart: on-failure    
volumes:
  pg_data:
